package com.vteam.soter.edi.sdk.rule;

/**
 * Created by Administrator on 2017/7/21.
 */
public enum CODELIST {
    // 默认值，非EDI标准
    SYS_NONE,
    rAcctCurrencies,
    Factor,
    Currency,
    rfcChangeReason,
    rfcPaymentMethod,
//    tblFSBC:SellerNrList,
    MessageType,
//    FSBC:BuyerNameList,
//    FSBC:SellerNameList,
    rfcPurchaseOrderVerificationStatus,
    ServiceRequired,
    refMessageStatus,
    tblCurrency,
//    tblFSBC:SellerNameList,
//    tblFSBC:BuyerNrList,
    rfcResponse,
//    FSBC:SellerNrList,
    rfcPaymentConditions,
//    FSBC:BuyerNrList,
    rfcReason,
    rfcMessageType,
    Country,
    PaymentMethod,
    rfcVerificationRequestStatus,
    ActionTaken,
    PaymentConditions,
    InstructionStatus,
    PaymentChannel,
    rfcMessageFunction,
    Reason,
    rfcPurchaseOrderVerification,
    rfcVerificationReason,
    rfcVerificationRequestAction,
    MessageFunction,
    PaymentType,
    rfcPurchaseOrderCreditCoverLossSharing,
    DocumentPaid,
    DisputeReason,
    tblFactor,
    Request,
    DocumentType,
    DisputeStatus,
    DirectContactAllowed,
    rfcStatus,
    FSBC,
    Response,
    rfcRequest,
    rfcVerificationStatus,
    rfcCancellationRiskIncluded,
    BankChargesIncluded,
//    tblFSBC:BuyerNameList,
    rfcDocumentType
}
